FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3 && apt-get install -y python3-pip
RUN apt-get install -y nginx
RUN pip install django==3.0.0
WORKDIR /usr/share/nginx/html
COPY index.html .